#!/usr/bin/env bun
/**
 * Generate a Bun-embeddable workspace template pack module from the live
 * workspace-template tree (manifest-driven, no node_modules).
 *
 * Files are stored flat under generated/template-blobs/ as <sha256> to avoid
 * nested vendor dirs (.claude etc.) that some workspaces block.
 *
 * Usage:
 *   bun script/pack-workspace-template.ts
 *   bun script/pack-workspace-template.ts --out packages/spinosa-kernel/src/generated/template-pack.gen.ts
 */
import { mkdirSync, writeFileSync, chmodSync, existsSync, readFileSync, rmSync } from "node:fs"
import path from "node:path"
import {
  buildTemplatePackMeta,
  listFrameworkManifestFiles,
} from "../packages/spinosa-core/src/framework/template-pack.ts"
import { BINARY_WORKSPACE_LAUNCHER } from "../packages/spinosa-core/src/distribution/workspace-launcher.ts"
import { releaseTemplateInputs } from "./release/template-inputs"

const root = path.resolve(import.meta.dir, "..")
const templateRoot = path.join(root, "workspace-template")

function argValue(flag: string): string | undefined {
  const i = process.argv.indexOf(flag)
  if (i < 0) return undefined
  return process.argv[i + 1]
}

const outPath =
  argValue("--out") ??
  path.join(root, "packages/spinosa-kernel/src/generated/template-pack.gen.ts")

const version =
  argValue("--version") ??
  (JSON.parse(readFileSync(path.join(root, "package.json"), "utf-8")) as { version: string }).version

const forwarderPath = path.join(templateRoot, ".bin", "spinosa")
mkdirSync(path.dirname(forwarderPath), { recursive: true })
writeFileSync(forwarderPath, BINARY_WORKSPACE_LAUNCHER, { mode: 0o755 })
chmodSync(forwarderPath, 0o755)

const files = releaseTemplateInputs(root, listFrameworkManifestFiles(templateRoot))
if (files.some((f) => f.relativePath.includes("node_modules"))) {
  throw new Error("template pack must not include node_modules")
}
if (files.some((f) => f.relativePath.includes("/.git/") || f.relativePath === ".git")) {
  throw new Error("template pack must not include .git")
}

const meta = buildTemplatePackMeta(version, files)
const blobDir = path.join(root, "packages/spinosa-kernel/src/generated/template-blobs")
rmSync(blobDir, { recursive: true, force: true })
mkdirSync(blobDir, { recursive: true })

const importLines: string[] = []
const entryLines: string[] = []

files.forEach((file, i) => {
  const dest = path.join(blobDir, `${file.sha256}.bin`)
  if (!existsSync(dest)) {
    writeFileSync(dest, readFileSync(file.sourcePath))
  }
  const relFromGen = path.relative(path.dirname(outPath), dest).replaceAll("\\", "/")
  const spec = relFromGen.startsWith(".") ? relFromGen : `./${relFromGen}`
  importLines.push(`import file_${i} from ${JSON.stringify(spec)} with { type: "file" };`)
  entryLines.push(
    `  { path: ${JSON.stringify(file.relativePath)}, mode: ${file.mode}, sha256: ${JSON.stringify(file.sha256)}, contentPath: file_${i} },`,
  )
})

const moduleSource = `/* AUTO-GENERATED by script/pack-workspace-template.ts — do not edit */
// @ts-nocheck
${importLines.join("\n")}

export const templatePack = {
  version: ${JSON.stringify(meta.version)},
  packId: ${JSON.stringify(meta.packId)},
  files: [
${entryLines.join("\n")}
  ],
} as const
`

mkdirSync(path.dirname(outPath), { recursive: true })
writeFileSync(outPath, moduleSource)
writeFileSync(
  path.join(path.dirname(outPath), "template-pack-meta.json"),
  `${JSON.stringify({ version: meta.version, packId: meta.packId, fileCount: files.length }, null, 2)}\n`,
)

console.log(`packed ${files.length} files → ${outPath}`)
console.log(`packId=${meta.packId}`)
console.log(`version=${meta.version}`)
